services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
    env_file:
      - ./prod.env
    networks:
      - siga-fcen
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    container_name: nginx
    expose:
      - "80"
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
    networks:
      - siga-fcen

networks:
  siga-fcen:
    external: true