services:
  nextjs:
    build:
      context: ./
      dockerfile: Dockerfile.build
    container_name: nextjs
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./:/src
    env_file:
      - .env.prod
    networks:
      - front-red

networks:
  front-red:
    external: true