services:
  nextjs:
    image: alwos19/siga-nextjs:1.0.0
    container_name: nextjs
    mem_limit: 300m
    env_file:
      - ./prod.env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - siga-fcen

  nginx:
    image: alwos19/siga-nginx:1.0.0
    container_name: nginx
    volumes:
      - ./certs:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
      - "80:80"
    expose:
      - "80"
    restart: always
    networks:
      - siga-fcen
    mem_limit: 100m

  cert-generator:
    image: alpine:latest
    container_name: cert-generator
    volumes:
      - ./certs:/certs
      - ./openssl.cnf:/etc/ssl/openssl.cnf
      - ./generate-certificates.sh:/generate-certificates.sh
    command: /generate-certificates.sh
    networks:
      - siga-fcen

networks:
  siga-fcen:
    external: true

volumes:
  ssl-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certs
