# Usar una imagen base de Node.js
FROM node:22-slim

# Establecer el directorio de trabajo
WORKDIR /src

# Copiar los archivos necesarios
COPY package.json package-lock.json ./
RUN npm install

# Copiar el archivo de variables de entorno
COPY .env.prod .env

# Copiar el resto del código fuente
COPY src ./src
COPY next.config.mjs ./
COPY tsconfig.json ./
COPY tailwind.config.ts ./
COPY postcss.config.mjs ./

# Construir la aplicación Next.js
RUN npm run build

# Exponer el puerto del frontend
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "start"]
