services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        NEXT_PUBLIC_API_URL: "https://backend/api/v1"
    container_name: nextjs
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./:/src
    env_file:
      - ./prod.env
    networks:
      - front-red

networks:
  front-red:
    external: true