services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/src/app
      - /src/app/node_modules
    env_file:
      - ./.env
    networks:
      - siga-fcen
    command: ["npm", "run", "dev"]

networks:
  siga-fcen:
    external: true