services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/src/app
      - /src/app/node_modules
    env_file:
      - ./.env
    networks:
      - front-red
    command: ["npm", "run", "dev"]

networks:
  front-red:
    external: true