FROM node:22.14.0-alpine

WORKDIR /src/app

# Copia solo los archivos de configuración y las dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY .. ..

# Define las variables de entorno para desarrollo
ENV NODE_ENV=development

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]