services:
  nextjs:
    build:
      context: ../
      dockerfile: Dockerfile.build
    ports:
      - "3000:3000"
    container_name: nextjs
    networks:
      - siga-fcen
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile.prod
    expose:
      - "80"
    ports:
      - "80:80"
    restart: always
    networks:
      - siga-fcen
    mem_limit: 100m

networks:
  siga-fcen:
    external: true