import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SessionProvider } from "@/core/providers/SessionProvider";
import SessionLayout  from "@/components/layouts/SessionLayout";
import { LoadingProvider } from "@/core/providers/LoadingProvider";
import Loading from "@/components/atoms/loading/Loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="es">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingProvider>
          <SessionProvider>
            <SessionLayout>
              {children}
            </SessionLayout>
          </SessionProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}

export default RootLayout;