import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import {SessionProvider} from "@/core/providers/SessionProvider";
import { SideNavItem } from "@/components/molecules/Navitem/Navitem";
import Sidebar from "@/components/organisms/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <div className="flex">
            <Sidebar />
            {children}
          </div>
          
        </SessionProvider>
      </body>
    </html>
  );
}
