FROM nginx:1.28.0-alpine

# Crear un usuario no privilegiado
#RUN addgroup --system nginx && adduser --system --ingroup nginx nginx

# Copiar la configuración de Nginx
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Crear y asignar permisos a los directorios necesarios
RUN mkdir -p /var/run/nginx && \
    mkdir -p /var/cache/nginx && \
    mkdir -p /var/log/nginx && \
    chown -R nginx:nginx /var/run/nginx /var/cache/nginx /var/log/nginx /etc/nginx

# Cambiar al usuario no privilegiado
USER nginx

# Exponer el puerto 80
EXPOSE 80

# Comando de inicio
CMD ["nginx", "-g", "daemon off;"]